extends Object
class_name WaiterConst


const STATE = {
	IDLE = 0,
	GO_TO_GUEST = 1,
	WAIT_FOR_GUEST = 2,
	GO_TO_KITCHEN = 3,
	SEND_ORDER_TO_CHEF = 4,
	BRING_FOOD_TO_GUEST = 5,
	SEND_FOOD_TO_GUEST = 6,
	GO_TO_IDLE_POS = 7,
	GO_TO_GUEST_FOR_PAYMENT = 8,
	CREATE_PAYMENT = 9,
	PREPARE_TO_IDLE = 10
}

const STATE_NAME = [
	"IDLE",
	"GO_TO_GUEST",
	"WAIT_FOR_GUEST",
	"GO_TO_KITCHEN",
	"SEND_ORDER_TO_CHEF",
	"BRING_FOOR_TO_GUEST",
	"SEND_FOOD_TO_GUEST",
	"GO_TO_IDLE_POS",
	"GO_TO_GUEST_FOR_PAYMENT",
	"CREATE_PAYMENT",
	"PREPARE_TO_IDLE"
]
