extends Object
class_name WaiterConst

const STATE = {
	GET_ORDER = 0,
	IDLE = 1,
	WALK_BACK = 2,
	WALK_BACK_WITH_PLATE = 3,
	WALK_FRONT = 4,
	WALK_FRONT_WITH_1_PLATE = 5,
	WALK_FRONT_WITH_2_PLATES = 6,
	WALK_FRONT_WITH_MENU = 7,
	WALK_SIDE = 8,
	WALK_SIDE_WITH_MENU = 9,
	WALK_SIDE_WITH_PLATE = 10,
}
